# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [1]:
# import NumPy into Python
import numpy as np


# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001, size = (1000,20))
# print the shape of X
print(X)


[[1129 1342 2375 ... 3474 2883 3942]
 [3765 4018 3950 ...   82  235 4317]
 [3643 4513 2798 ... 3637 3658  298]
 ...
 [ 849 2037 2085 ... 3783  325 1168]
 [2965 3187 3676 ... 3197 2806 1835]
 [2499 1350  535 ...  472 1986 3300]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [2]:
# Average of the values in each column of X
ave_cols = X.mean(axis = 0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis = 0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [3]:
# Print the shape of ave_cols
print(ave_cols.shape)


# Print the shape of std_cols
print(std_cols.shape)

(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [4]:
# Mean normalize X
X_norm = (X - ave_cols) / std_cols

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [5]:
# Print the average of all the values of X_norm
print(X_norm)

# Print the average of the minimum value in each column of X_norm
print(X_norm.min(axis = 0))

# Print the average of the maximum value in each column of X_norm
print(X_norm.max(axis = 0))

[[-0.98470495 -0.83353451 -0.1269568  ...  0.64394134  0.27955168
   1.00560212]
 [ 0.80839481  1.06663148  0.96855375 ... -1.70543854 -1.54856265
   1.26300002]
 [ 0.72540613  1.41811958  0.16726603 ...  0.75683901  0.8145927
  -1.49561908]
 ...
 [-1.17517078 -0.34003101 -0.32866986 ...  0.85796208 -1.48642886
  -0.89845595]
 [ 0.26420672  0.47655751  0.77796969 ...  0.45208455  0.22639277
  -0.44063089]
 [-0.05278284 -0.8278539  -1.40679135 ... -1.43531526 -0.33971515
   0.56493691]]
[-1.75201016 -1.77651674 -1.76848372 -1.74661453 -1.64255206 -1.73416206
 -1.79371586 -1.70096338 -1.79735463 -1.73028691 -1.76419606 -1.81447738
 -1.7693546  -1.81826545 -1.69745595 -1.67940366 -1.7529691  -1.75322958
 -1.70942015 -1.69810543]
[1.64440377 1.76179684 1.69819855 1.7746948  1.76062097 1.72398037
 1.68816811 1.73177825 1.7071817  1.69820791 1.69407828 1.69310313
 1.65723637 1.65687966 1.75415878 1.75107834 1.72265548 1.70019261
 1.74107662 1.72700264]


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [6]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([0, 1, 3, 4, 2])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [8]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row, col = X_norm.shape
row_indices = np.random.permutation(row)
print(row_indices)

[660 155 175 168 179 269 143 611 426 739  20 424 402 547  57 760  93 285
 751 641 752 476 390 743 471 258 342 740 295 540 103 853 391 291 352 620
 364  14 888 800  26 312 380 596 519  17 282 413 372  65 573  63 656 870
 835 341 990 892 363 802 478 172 777 535 568 579 603  74 526  92 208 948
 943 401 334 952 286  84 704 836 908  81 480 530 293 644 477 796 320 163
 978 927 559 953 565 481 524 340 728 156 200 191 605 995 216 464 551 582
  59 539 371 583 273  98 988 429 789 868 872 229 529 842 294 125 721 859
 246 375 178 520 665 367 358 837 574 844 177 860 621 709 845 321  38   7
  39 599 767 893  80 514 841 715 440  66 630 448 446 498 631 906 968 896
 824 920 820  79 902 693 225 880 435 716 195  82   0 935 305 301 209 394
 766 729 964 992 256 899 769 482  43 410 288 270 652 602 456 863 362 732
 495  64 572 894 233  33 354 723  96 338 300 790 808 970 851 434 701 897
  86 763 355 308 815 886 330 353 564 242 231 190 137 438 162 866 975 710
 852  70 578 591 160 822 628   9 403 774 205 532 50

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [9]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.


# Create a Training Set
X_train = X_norm[row_indices[0:600]]


# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[600:800]]

# Create a Test Set
X_test = X_norm[row_indices[800:1000]]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [10]:
print(X_train.shape)
print(X_crossVal.shape)
print(X_test.shape)

(600, 20)
(200, 20)
(200, 20)
